# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.define "trusty-ckan" do |trusty|
    trusty.vm.box = "bento/ubuntu-14.04"
    trusty.vm.network "forwarded_port", guest: 80, host: 6080
    trusty.vm.network "forwarded_port", guest: 5000, host: 6050
    trusty.vm.network "forwarded_port", guest: 8983, host: 6983
    trusty.vm.network "private_network", ip: "192.168.33.10"
    trusty.vm.synced_folder "data", "/home/vagrant/data"
    trusty.vm.provision :shell, :path => "data/system_setup.sh", :args=>[ENV['ver']]

  end

  config.vm.define "precise-ckan" do |precise|
    precise.vm.box = "bento/ubuntu-12.04"
    precise.vm.network "forwarded_port", guest: 80, host: 6080
    precise.vm.network "forwarded_port", guest: 5000, host: 6050
    precise.vm.network "forwarded_port", guest: 8983, host: 6983
    precise.vm.network "private_network", ip: "192.168.33.11"
    precise.vm.synced_folder "data", "/home/vagrant/data"
    precise.vm.provision :shell, :path => "data/system_setup.sh", :args=>[ENV['ver']]
  end

  config.vm.define "xenial-ckan" do |xenial|
    xenial.vm.box = "bento/ubuntu-16.04"
    xenial.vm.network "forwarded_port", guest: 80, host: 6080
    xenial.vm.network "forwarded_port", guest: 5000, host: 6050
    xenial.vm.network "forwarded_port", guest: 8983, host: 6983
    xenial.vm.network "private_network", ip: "192.168.33.12"
    xenial.vm.synced_folder "data", "/home/vagrant/data"
    xenial.vm.provision :shell, :path => "data/system_setup.sh", :args=>[ENV['ver']]
  end
  config.vm.define "bionic-ckan" do |bionic|
    bionic.vm.box = "ubuntu/bionic64"
    bionic.vm.network "forwarded_port", guest:80, host:6080
    bionic.vm.network "forwarded_port", guest:5000, host:6050
    bionic.vm.network "forwarded_port", guest:8983, host:6983
    bionic.vm.network "private_network", ip: "192.168.33.14"
    bionic.vm.synced_folder "data", "/home/vagrant/data"
  end

end
